name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23.x
    - name: Cross build
      run: make cross
    - name: Create a Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag: ${{ github.ref }}
        title: Release ${{ github.ref }}
    - name: Upload
      run: make upload
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
